---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install required packages
  apt:
    name:
      - curl
      - git
      - apache2
      - postgresql-client
    state: present
  become: true

- name: Ensure apache2 service is properly configured
  shell: |
    mkdir -p /var/run/apache2
    chown www-data:www-data /var/run/apache2
  become: true
  notify:
    - restart apache2

- name: enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  become: true
  notify:
    - restart apache2

- name: Install Node.js
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
    apt-get install -y nodejs
  args:
    creates: /usr/bin/node
  become: true

- name: Install application dependencies
  shell: |
    cd /var/www/todolist
    npm install
  become: true
  become_user: "{{ ansible_user }}"

- name: Update database configuration
  template:
    src: database.js.j2
    dest: /var/www/todolist/src/config/database.js
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: true

- name: Configure Apache to proxy requests to Node.js
  template:
    src: todolist.conf.j2
    dest: /etc/apache2/sites-available/todolist.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - proxy
    - proxy_http
    - proxy_balancer
    - lbmethod_byrequests
  become: true
  notify:
    - restart apache2

- name: Enable todolist site
  command: a2ensite todolist.conf
  become: true
  notify:
    - restart apache2

- name: Disable default Apache site
  command: a2dissite 000-default.conf
  become: true
  ignore_errors: true
  notify:
    - restart apache2

- name: Arrêter les processus Node.js existants
  shell: |
    pkill -f "node" || true
    sleep 2
  become: true
  ignore_errors: true

- name: Créer le script de démarrage
  copy:
    content: |
      #!/bin/bash
      
      # Changer de répertoire
      cd /var/www/todolist
      
      # Définir les variables d'environnement
      export NODE_ENV=development
      
      # Démarrer l'application
      exec node -r sucrase/register src/server.js >> app.log 2>&1
    dest: /var/www/todolist/start-app.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Créer le script de surveillance
  copy:
    content: |
      #!/bin/bash
      
      # Arrêter les processus existants
      pkill -f "node -r sucrase/register" || true
      sleep 2
      
      # Démarrer l'application
      cd /var/www/todolist
      nohup ./start-app.sh > /dev/null 2>&1 &
      echo "Application démarrée avec PID: $!"
      
      # Surveiller l'application et la redémarrer si nécessaire
      while true; do
        if ! pgrep -f "node -r sucrase/register" > /dev/null; then
          echo "Application arrêtée, redémarrage..."
          cd /var/www/todolist
          nohup ./start-app.sh > /dev/null 2>&1 &
          echo "Application redémarrée avec PID: $!"
        fi
        sleep 5
      done
    dest: /var/www/todolist/run-app.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Démarrer l'application avec surveillance
  shell: |
    cd /var/www/todolist
    nohup ./run-app.sh > /dev/null 2>&1 &
  become: true
  become_user: "{{ ansible_user }}"
  async: 60
  poll: 0
